[package]
name = "rdkit"
version = "0.2.3"
edition = "2021"
authors = ["Xavier Lange <xrlange@gmail.com>"]
license = "MIT"
description = "High level RDKit functionality for rust"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cxx = "1"
log = "0.4"
rdkit-sys = "0.2.6"
#rdkit-sys = { path = "../rdkit-sys"}